# -*- coding: utf-8 -*-
"""Aula1_Primeiro_Projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q36wfCPf21yw8z_FJ48Bb53aIiKiPcw3

# **SEMPRE UTILIZE VARIAVEIS DIFERENTES!!**

O Valor a ser impresso será **etec**, não há *variaveis* envolvidas
"""

print("ETEC Jales - CALCULADORA ~ PYTHON")
# com três linhas
# função eval() resolve a expressão matematica dentro da variavel estabelecida

expressao_matematica = input("Digite uma expressão matematica: ")

resultado = eval(expressao_matematica)

print("O resultado é", resultado)

print("ETEC Jales")
print("Ola Mundo!")
print("01/03/2024")

"""Utilizando **PRINT**("texto") + ***VARIAVEIS***


"""

a = 2
print(a)
b = 2 + 2
print(b)
c = "Guilherme"
print(c)

"""Some a + b"""

a = 10
b = 3
c = a + b
print(c)

valor1 = 50
valor2 = 10
soma = valor1 + valor2
subtraia = valor1 - valor2
multiplica = valor1 * valor2
divisao = valor1 / valor2
print("soma", soma)
print("subtraia", subtraia)
print("multiplica", multiplica)
print("divisao", divisao)

a = "Guilherme"
b = "Pereira"
c = "Fonseca é foda nékkkkkk"
print(a,b,c)

"""**LISTA [ ]** = matriz (0,1,2,3...)"""

lista = [10, "Banana", 3]
# matrizes começa com numero 0,1,2,3...
print(lista[0])

# defina o tipo do numero a ser inserido
# não precisa perguntar sobre o string (texto)
# SOMA
valor1_1 = int(input("Insira1 um numero: "))
valor1_2 = int(input("Insira um numero: "))
soma = valor1_1 + valor1_2
print(soma)

# SUBTRAÇÃO
valor2_1 = int(input("Insira1 um numero: "))
valor2_2 = int(input("Insira um numero: "))
subtração = valor2_1 - valor2_2
print(subtração)

# MULTIPLICAÇÃO
valor3_1 = int(input("Insira1 um numero: "))
valor3_2 = int(input("Insira um numero: "))
multiplicação = valor3_1 * valor3_2
print(multiplicação)

# DIVISÃO
valor4_1 = float(input("Insira1 um numero: "))
valor4_2 = float(input("Insira um numero: "))
divisão = valor4_1 / valor4_2
print(divisão)

# POTENCIAÇÃO
valor5_1 = int(input("Insira1 um numero: "))
valor5_2 = int(input("Insira um numero: "))
potenciação = valor5_1 ** valor5_2
print(potenciação)