# -*- coding: utf-8 -*-
"""Aula4_Boletim.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZIY17KSfqD7OKQyiWXtQEDsBl5RjHhK

###**BOLETIM**

* <code>len</code> (lenght) = *tamanho*
* [] = matriz/array
* {} = dicionário

<b> trocando o 'for i in range(2) para range(4)', ele repete para 4 notas pra cada disciplina </b>
"""

# Função para calcular a média das notas
# len (lenght) = tamanho
# [] = matriz/array

def calcular_media(notas):
    soma = sum(notas)
    quantidade = len(notas) # conta a quantidade de notas
    return soma / quantidade

# Lista de disciplinas

disciplinas = ["Fundamentos de Banco de Dados", "Programação de Computadores"]

# Dicionário para armazenar as notas de cada disciplina

notas_por_disciplina = {}

# Solicitar e armazenar as notas de cada disciplina

for disciplina in disciplinas:
    notas_disciplina = []

    for i in range(4):  # Limitado a quatro notas por disciplina.
        nota = float(input(f"Digite a nota {i+1} de {disciplina}: "))
        notas_disciplina.append(nota)
    notas_por_disciplina[disciplina] = notas_disciplina

# Calcular a média geral e médias por disciplina.

medias_por_disciplina = {disciplina: calcular_media(notas) for disciplina, notas in notas_por_disciplina.items()}
media_geral = calcular_media(list(medias_por_disciplina.values()))

# Imprimir o boletim escolar

print("\n BOLETIM ESCOLAR")
print("===============================================================================")
print("{:<30} {:<10} {:<10} {:<10} {:<10} {:<10}".format("Disciplina", "Nota 1", "Nota 2", "Nota 3", "Nota 4", "Média"))
print("-------------------------------------------------------------------------------")
for disciplina, notas in notas_por_disciplina.items():
    print("{:<30} {:<10} {:<10} {:<10} {:<10} {:<10.2f}".format(disciplina, notas[0], notas[1], notas[2], notas[3], medias_por_disciplina[disciplina]))
print("----------------------------------------------------------------------------------")
print("{:<30} {:<10.2f}".format("Média Geral", media_geral))
print("====================================================================================")