# -*- coding: utf-8 -*-
"""Aula3_Função_e_Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AY8yPJg2uBJEZpnhuY0kZi2eIj-9nY0J

###**DEF**
"""

# (a,b) = são as variaveis.
# break interrope o loop, sai do programa.
# ==: significa '=' (igual)

def adicao(num1, num2):
    return num1+num2

def subtracao(num1, num2):
    return num1-num2

def multiplicacao(num1, num2):
    return num1*num2

def divisao(num1, num2):
    if num2 == 0:
        return "Erro! divisão por 0!!"
    else:
        return num1 / num2

def menu():
    print("\n \t Calculadora - ETEC")
    print("\n1. Adição")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Sair")

while True:
    menu()
    escolha = input("\nEscolha uma operação (1-5):")
    if escolha == '5':
        print("Saindo da Calculadora!!!")
        break

    try:
        num1 = float(input("Digite o número 1:"))
        num2 = float(input("Digite o número 2:"))
    except ValueError:
        print("Insira o valor correto!!!")
        continue

    if escolha == '1':
        print("\nResultado:", adicao(num1, num2))
    elif escolha == '2':
        print("\nResultado", subtracao(num1, num2))
    elif escolha == '3':
        print("\nResultado", multiplicacao(num1, num2))
    elif escolha == '4':
        print("\nResultado", divisao(num1, num2))
    else:
        print("Opção inválida. Por favor, escolha uma opção válida.")