# -*- coding: utf-8 -*-
"""Aula2_Laços_e_Jogo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13C3JvjFGA0BTmsEPOEs8rnWAPC29kIOi

###**FOR** - *ETEC*
"""

# 08/03/2024
# exemplo de lista para iterar:
# iterar = repetir.
# matriz sempre começa com zero
lista = [1, 2, 3, 4, 5]

# Laço 'for' para percorrer a lista:
print("Usando laço 'for': ")
for elemento in lista:
    print(elemento)

lista = [1, 2, 3, "gui", 5]

print("Usando laço 'for': ")
for elemento in lista:
    print(lista[3])

"""###**WHILE** - *ETEC*"""

# Laço 'while' para imprimir os números de 1 a 5
# faz em sequencia, adicionando +=
# não é uma matriz, mas sim uma sequencia normal.
# \n = pula a linha.

print("\nUsando o laço 'while':")
contador = 1
while contador <= 100:
    print(contador)
    contador += 1

"""###**FOR e RANGE** - *ETEC*"""

# outra forma de laço
# range se baseia na reta númerica.
# x = número elevado (**) a 2

print("\nUsando a compreensão de lista:")
quadrados = [x ** 2 for x in range(1, 6)]
print(quadrados)

"""###***JOGO DE ADIVINHAÇÃO*** - *ETEC*
* <b>WHILE
* IF/ELIF/ELSE </b>


"""

# Biblioteca que gera números aleatórios.
# o 'f' em 'print' e a função 'format()'
# só vai sair do laço de repetição se você acertar.
import random

# Gerar um número aleatório entre 1 e 100.
numero_aleatorio = random.randint(1, 100)

# Iniciar o loop de adivinhação:
adivinhou = False # Booleano
tentativas = 0

print("Bem-vindo ao jogo de Adivinhação!!")
print("Tente adivinhar o número entre 1 e 100.")

while not adivinhou:
    # Pedir ao usuário para adivinhar
    tentativa = int(input("Digite o seu palpite:"))

    # Verificar se o palpite está correto
    if tentativa == numero_aleatorio:
        tentativas += 1
        print(f"Parabéns! você acertou o número em {tentativas} tentativas.")
        adivinhou = True # Booleano
    elif tentativa < numero_aleatorio:
        print("O número é maior, tente novamente.")
        tentativas += 1
    else:
        print("O número é menor, tente novamente.")
        tentativas += 1